# On any change to the ./website/ folder here, push it to the campbelllustblackwell.github.io site

name: push_website_to_io

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config --global user.email robert.lugg@gmail.com
          git config --global user.name robertlugg
      - run: git clone --single-branch --branch main https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.com.git source
      - run: git clone --single-branch --branch main https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.github.io.git destination
      - run: ls
      - run: cp -R source/website/* destination
      - run: ls destination
      - run: |
          cd destination
          git add --all
          # git diff-index : to avoid doing the git commit failing if there are no changes to be commit
          git diff-index --quiet HEAD || git commit --message "Integration on `date` from website directory"
          git push origin --set-upstream main
